const path = require('path');
const fs = require('fs');
const showdown = require('showdown');
const converter = new showdown.Converter();
const mdpath = path.resolve(__dirname, 'src/content.md');
const outpath = path.resolve(__dirname, 'src/templates/content.html');
const md = fs.readFileSync(mdpath).toString();
const html = converter.makeHtml(md) + '\n';
fs.writeFileSync(outpath, html);
console.log('built content.html');